@echo off
echo Starting Data Extractor...
echo Installing dependencies...
pip install -r requirements.txt

echo Setting up Playwright...
playwright install chromium

echo Starting application...
python start.py

pause